### ISSUE TITLE
Use separate image names for slim and fat images.

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc-builder#8]
Sometimes we just want to use the latest slim or fat image. For example, when building the docs locally. Updating versions in README and saved commands is a huge pain.

I see two options here:

* Use two separate image names: `doc-builder-slim:latest` and `doc-builder-fat:latest`
* Use tags without numbers for the latest versions: `doc-builder:slim` and `doc-builder:fat`

**Comment by artembo** [comment]
The second option is already implemented

**Comment by artembo** [comment]
try:
```bash
docker run --rm -it tarantool/doc-builder:fat
```
or 
```bash
docker run --rm -it tarantool/doc-builder:slim
```
